import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
// import Container from "@/components/Container";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LanguageProvider } from "@/components/LanguageChange";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  console.log(messages);

  return (
    <html lang="en">
      <body
        className={`ltr:${geistSans.variable} ltr:${geistMono.variable} ${cairo.className} antialiased bg-background`}
      >
        <NextIntlClientProvider messages={messages}>
          <div className="flex flex-col min-h-screen gap-20">
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
          <LanguageProvider />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
